// client/src/components/Home.vue
<script setup>
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import MainLayout from '@/layouts/MainLayout.vue';
const apiPath = import.meta.env.VITE_API_PATH;
const businesses = ref(null);

onMounted(async () => {
  try {
    const response = await fetch(`${apiPath}/businesses`);
    const bizzData = await response.json();
    businesses.value = bizzData;
  } catch (error) {
    console.error(`Failed to get businesses`);
  }
});

</script>

<template>
  <MainLayout>
    <section class="flex justify-center px-10 py-10 font-sans">
      <div class="flex flex-wrap items-center gap-16 w-full max-w-6xl">

        <div class="flex-1 min-w-[300px] ">
          <h3 class="text-5xl font-bold leading-tight mb-6">
            Exposing Discriminatory Hospitality
          </h3>
          <p class="text-lg text-gray-500 mb-8 ">
            <strong>No Locals</strong> is a website that helps locals to point out
            restaurants, hotels or accommodations that do not serve locals.
          </p>
          <router-link
            to="/businesses/submit"
            class="bg-black text-white px-8 py-4 rounded-xl font-bold transition-colors duration-300 hover:bg-yellow-400 hover:text-black"
          >
            Report a business
          </router-link>
        </div>

        <div class="flex-1 min-w-[250px] flex justify-center overflow-hidden">
          <img
            src="https://res.cloudinary.com/dfeqksqvh/image/upload/v1777589936/IMG_0872_vwyw3z.jpg"
            alt="Hero Image"
            class="w-full max-w-[350px] h-auto object-cover rounded-lg"
          />
        </div>

      </div>
    </section>
  </MainLayout>
</template>

// client/src/pages/Home.tsx
import { Link } from "react-router-dom";
import MainLayout from "../layouts/MainLayout";

const Home = () => {
  return (
    <>
      <MainLayout>
        <div className="flex items-center justify-center min-h-screen">
          <div className="flex flex-wrap items-center justify-between gap-10 w-full max-w-7xl mx-auto px-8">
            {/* Left Section */}
            <section className="flex-1 min-w-[300px] flex flex-col justify-center">
              <h1 className="text-6xl font-black leading-tight mb-6">
                Exposing
                <br />
                Discriminatory
                <br />
                Hospitality
              </h1>
              <p className="text-gray-600 mb-8 text-lg max-w-md leading-relaxed">
                <span className="text-black font-bold">No Locals</span> is a
                website that helps locals to point out restaurants, hotels or
                accommodations that do not serve locals.
              </p>
              <Link
                to="/report"
                className="bg-black text-white px-8 py-3 rounded-full font-bold w-fit hover:bg-gray-800 transition"
              >
                Report a business
              </Link>
            </section>

            {/* Right Section - Image */}
            <div className="flex-1 flex justify-end">
              <img
                className="w-full max-w-sm h-auto object-cover rounded-3xl shadow-2xl"
                src="https://res.cloudinary.com/dfeqksqvh/image/upload/v1777589936/IMG_0872_vwyw3z.jpg"
                alt="main-image"
              />
            </div>
          </div>
        </div>
      </MainLayout>
    </>
  );
};

export default Home;
