// client/src/layouts/MainLayout.tsx
import { useEffect, useState, type ReactNode } from "react";
import { Link, useNavigate } from "react-router-dom";

interface MainLayoutProps {
  children: ReactNode;
}

const MainLayout = ({ children }: MainLayoutProps) => {
  const navigate = useNavigate();
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [username, setUsername] = useState("");
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  useEffect(() => {
    const token = localStorage.getItem("token");
    const storedName = localStorage.getItem("username");
    if (token && storedName) {
      setIsLoggedIn(true);
      setUsername(storedName);
    }
  }, []);

  const handleLogout = () => {
    localStorage.removeItem("token");
    localStorage.removeItem("username");
    setIsLoggedIn(false);
    setMobileMenuOpen(false);
    navigate("/login");
  };

  const toggleMobileMenu = () => {
    setMobileMenuOpen(!mobileMenuOpen);
  };

  return (
    <div className="flex flex-col min-h-screen">
      {/* Header / Navbar */}
      <nav className="bg-white border-b border-gray-200 px-4 py-3 shadow-sm">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          {/* Logo */}
          <Link to="/" className="flex-shrink-0">
            <img
              src="https://res.cloudinary.com/dfeqksqvh/image/upload/v1777574904/No_Locals_1_lgu0n2.png"
              height="40"
              alt="Logo"
              className="h-10 w-auto"
            />
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center gap-8">
            <Link
              to="/about"
              className="text-gray-700 hover:text-black font-medium transition"
            >
              About
            </Link>
            <Link
              to="/businesses"
              className="text-gray-700 hover:text-black font-medium transition"
            >
              Businesses
            </Link>

            {isLoggedIn ? (
              <div className="flex items-center gap-4">
                <span className="text-sm text-gray-600">
                  Logged in as: <strong>{username}</strong>
                </span>
                <button
                  onClick={handleLogout}
                  className="px-4 py-2 bg-black text-white text-sm font-semibold rounded hover:bg-gray-800 transition"
                >
                  Logout
                </button>
              </div>
            ) : (
              <Link
                to="/register"
                className="text-gray-700 hover:text-black font-medium transition"
              >
                Register
              </Link>
            )}
          </div>

          {/* Mobile Menu Toggle */}
          <button
            onClick={toggleMobileMenu}
            className="md:hidden flex flex-col gap-1.5 p-2 hover:bg-gray-100 rounded"
          >
            <span
              className={`w-6 h-0.5 bg-black transition-all ${
                mobileMenuOpen ? "rotate-45 translate-y-2" : ""
              }`}
            />
            <span
              className={`w-6 h-0.5 bg-black transition-all ${
                mobileMenuOpen ? "opacity-0" : ""
              }`}
            />
            <span
              className={`w-6 h-0.5 bg-black transition-all ${
                mobileMenuOpen ? "-rotate-45 -translate-y-2" : ""
              }`}
            />
          </button>
        </div>

        {/* Mobile Navigation */}
        {mobileMenuOpen && (
          <div className="md:hidden mt-4 pb-4 border-t border-gray-200 pt-4">
            <div className="flex flex-col gap-3">
              <Link
                to="/about"
                onClick={() => setMobileMenuOpen(false)}
                className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded transition"
              >
                About
              </Link>
              <Link
                to="/businesses"
                onClick={() => setMobileMenuOpen(false)}
                className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded transition"
              >
                Businesses
              </Link>

              {isLoggedIn ? (
                <>
                  <div className="px-4 py-2 text-sm text-gray-600">
                    Logged in as: <strong>{username}</strong>
                  </div>
                  <button
                    onClick={() => {
                      handleLogout();
                      setMobileMenuOpen(false);
                    }}
                    className="px-4 py-2 bg-black text-white text-sm font-semibold rounded hover:bg-gray-800 transition"
                  >
                    Logout
                  </button>
                </>
              ) : (
                <Link
                  to="/register"
                  onClick={() => setMobileMenuOpen(false)}
                  className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded transition"
                >
                  Register
                </Link>
              )}
            </div>
          </div>
        )}
      </nav>

      {/* Main Content Area */}
      <main className="flex-grow max-w-7xl mx-auto w-full px-4 py-8">
        {children}
      </main>

      {/* Footer */}
      <footer className="bg-black text-white py-8 mt-auto">
        <div className="max-w-7xl mx-auto px-4">
          {/* Main footer content */}
          <div className="grid grid-cols-2 md:grid-cols-3 gap-1 pb-8">
            {/* Left side - Logo and tagline */}
            <div>
              <Link to="/" className="flex-shrink-0">
                <img
                  src="https://res.cloudinary.com/dfeqksqvh/image/upload/v1777574904/No_Locals_1_lgu0n2.png"
                  height="25"
                  className="h-6 w-auto mb-4 invert"
                  alt="Logo"
                />
              </Link>
              <p className="text-gray-400 text-sm">
                Exposing discriminatory practices in hospitality.
              </p>
            </div>

            {/* Center - Platform Links */}
            <div>
              <h6 className="text-sm font-semibold mb-3">Platform</h6>
              <ul className="space-y-2">
                <li>
                  <Link
                    to="/businesses"
                    className="text-gray-400 hover:text-white text-sm transition"
                  >
                    Find Businesses
                  </Link>
                </li>
                <li>
                  <Link
                    to="/report"
                    className="text-gray-400 hover:text-white text-sm transition"
                  >
                    Report an Incident
                  </Link>
                </li>
              </ul>
            </div>

            {/* Right - Community Links */}
            <div>
              <h6 className="text-sm font-semibold mb-3">Community</h6>
              <ul className="space-y-2">
                <li>
                  <Link
                    to="/resources"
                    className="text-gray-400 hover:text-white text-sm transition"
                  >
                    Resources
                  </Link>
                </li>
                <li>
                  <Link
                    to="/privacy"
                    className="text-gray-400 hover:text-white text-sm transition"
                  >
                    Privacy Policy
                  </Link>
                </li>
              </ul>
            </div>
          </div>

          {/* Footer divider and copyright */}
          <div className="border-t border-gray-700 pt-6">
            <p className="text-gray-400 text-sm text-center">
              &copy; 2026 No Locals. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default MainLayout;

// client/src/layouts/MainLayout.vue
<script setup>
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();
const isLoggedIn = ref(false);
const username = ref('');
const mobileMenuOpen = ref(false);

onMounted(() => {
  const token = localStorage.getItem('token');
  const storedName = localStorage.getItem('username');
  if (token && storedName) {
    isLoggedIn.value = true;
    username.value = storedName;
  }
});

const handleLogout = () => {
  localStorage.removeItem('token');
  localStorage.removeItem('username');
  isLoggedIn.value = false;
  mobileMenuOpen.value = false;
  router.push('/login');
};

const toggleMobileMenu = () => {
  mobileMenuOpen.value = !mobileMenuOpen.value;
};

</script>

<template>
  <header class="home-header">
    <div class="logo">
      <router-link to="/" @click="mobileMenuOpen = false">
        <img src="https://res.cloudinary.com/dfeqksqvh/image/upload/v1777574904/No_Locals_1_lgu0n2.png" alt="No Locals Logo" class="home-logo">
      </router-link>
    </div>

    <!-- Mobile Menu Toggle -->
    <button class="mobile-menu-btn" @click="toggleMobileMenu" v-if="mobileMenuOpen">
      ✕
    </button>
    <button class="mobile-menu-btn" @click="toggleMobileMenu" v-else>
      ☰
    </button>

    <!-- Desktop Navigation -->
    <div class="nav nav-desktop">
      <router-link to="/about" class="nav-link">About</router-link>
      <router-link to="/businesses" class="nav-link">Businesses</router-link>
      <div v-if="isLoggedIn" class="user-section">
        <span>Logged in as: <strong>{{ username }}</strong></span>
        <button @click="handleLogout" class="logout-btn">Logout</button>
      </div>
      <router-link v-else to="/register" class="nav-link">Register</router-link>
    </div>

    <!-- Mobile Navigation -->
    <div v-if="mobileMenuOpen" class="nav nav-mobile">
      <router-link to="/about" class="nav-link" @click="mobileMenuOpen = false">About</router-link>
      <router-link to="/businesses" class="nav-link" @click="mobileMenuOpen = false">Businesses</router-link>
      <div v-if="isLoggedIn" class="user-section-mobile">
        <span>Logged in as: <strong>{{ username }}</strong></span>
        <button @click="handleLogout" class="logout-btn">Logout</button>
      </div>
      <router-link v-else to="/register" class="nav-link" @click="mobileMenuOpen = false">Register</router-link>
    </div>
  </header>

  <main class="site-main">
    <slot />
  </main>

  <footer class="home-footer">
    <div class="footer-content">
      <div class="footer-brand">
        <router-link to="/">
          <img src="https://res.cloudinary.com/dfeqksqvh/image/upload/v1777574904/No_Locals_1_lgu0n2.png" alt="Logo" class="footer-logo">
        </router-link>
        <p>Exposing discriminatory practices in hospitality to ensure fair access for everyone.</p>
      </div>
      
      <div class="footer-links">
        <div class="link-group">
          <h4>Platform</h4>
          <p>Find Businesses</p>
          <p>Report an Incident</p>
          <p>Global Map</p>
        </div>
        <div class="link-group">
          <h4>Community</h4>
          <p>Resources</p>
          <p>Contribute</p>
          <p>Privacy Policy</p>
        </div>
      </div>
    </div>
    <div class="footer-bottom">
      <p>&copy; 2026 No Locals. All rights reserved.</p>
    </div>
  </footer>
</template>

<style scoped>
/* Header styles */
.home-header {
  font-family: inter;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px 80px;
  position: relative;
  background-color: #fff;
  border-bottom: 1px solid #e2e8f0;
}

.home-logo {
  height: 40px;
  width: auto;
}

.nav-desktop {
  display: flex;
  gap: 32px;
  align-items: center;
}

.nav-mobile {
  display: none;
}

.mobile-menu-btn {
  display: none;
  background: none;
  border: none;
  font-size: 24px;
  cursor: pointer;
  padding: 8px;
}

.nav-link {
  color: black;
  text-decoration: none;
  font-weight: 500;
  transition: color 0.3s;
}

.nav-link:hover {
  color: #666;
}

.user-section {
  display: flex;
  align-items: center;
  gap: 12px;
  font-size: 14px;
}

.logout-btn {
  background-color: #000;
  color: #fff;
  border: none;
  padding: 8px 16px;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 500;
  transition: background-color 0.3s;
}

.logout-btn:hover {
  background-color: #333;
}

.site-main {
  position: relative;
  width: 100%;
  max-width: 1200px;
  margin: 0 auto;
  min-height: 80vh;
}

/* Footer Styles */
.home-footer {
  background-color: #000;
  color: #fff;
  padding: 80px 80px 40px 80px;
  margin-top: 100px;
}

.footer-content {
  display: flex;
  justify-content: space-between;
  max-width: 1200px;
  margin: 0 auto;
  gap: 40px;
}

.footer-brand {
  max-width: 300px;
}

.footer-logo {
  height: 30px;
  filter: brightness(0) invert(1);
  margin-bottom: 20px;
  width: auto;
}

.footer-brand p {
  color: #aaa;
  font-size: 14px;
  line-height: 1.6;
}

.footer-links {
  display: flex;
  gap: 80px;
}

.link-group h4 {
  font-size: 16px;
  margin-bottom: 20px;
  font-weight: 600;
}

.link-group p {
  color: #aaa;
  font-size: 14px;
  margin-bottom: 12px;
  cursor: pointer;
  transition: color 0.3s ease;
}

.link-group p:hover {
  color: #fff;
}

.footer-bottom {
  max-width: 1200px;
  margin: 60px auto 0 auto;
  padding-top: 30px;
  border-top: 1px solid #333;
  text-align: center;
}

.footer-bottom p {
  color: #666;
  font-size: 12px;
}

/* Tablet (768px and below) */
@media (max-width: 768px) {
  .home-header {
    padding: 16px 20px;
  }

  .mobile-menu-btn {
    display: block;
  }

  .nav-desktop {
    display: none;
  }

  .nav-mobile {
    display: flex;
    flex-direction: column;
    position: absolute;
    top: 60px;
    left: 0;
    right: 0;
    background-color: #fff;
    border-bottom: 1px solid #e2e8f0;
    padding: 16px 20px;
    gap: 12px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    z-index: 1000;
  }

  .nav-link {
    padding: 8px 0;
  }

  .user-section-mobile {
    display: flex;
    flex-direction: column;
    gap: 12px;
    padding: 12px 0;
    border-top: 1px solid #e2e8f0;
  }

  .footer-content {
    flex-direction: column;
    gap: 32px;
  }

  .footer-links {
    gap: 40px;
    flex-wrap: wrap;
  }

  .home-footer {
    padding: 40px 20px 20px 20px;
    margin-top: 60px;
  }
}

/* Mobile (480px and below) */
@media (max-width: 480px) {
  .home-header {
    padding: 12px 16px;
  }

  .home-logo {
    height: 32px;
  }

  .mobile-menu-btn {
    font-size: 20px;
  }

  .nav-mobile {
    top: 50px;
    padding: 12px 16px;
    gap: 8px;
  }

  .user-section-mobile {
    padding: 8px 0;
    font-size: 12px;
  }

  .logout-btn {
    padding: 6px 12px;
    font-size: 12px;
  }

  .footer-brand {
    max-width: 100%;
  }

  .footer-logo {
    height: 24px;
  }

  .footer-brand p {
    font-size: 13px;
  }

  .footer-links {
    flex-direction: column;
    gap: 24px;
  }

  .link-group h4 {
    font-size: 14px;
    margin-bottom: 12px;
  }

  .link-group p {
    font-size: 13px;
    margin-bottom: 8px;
  }

  .footer-bottom {
    margin: 40px auto 0 auto;
    padding-top: 20px;
  }

  .footer-bottom p {
    font-size: 11px;
  }

  .home-footer {
    padding: 30px 16px 16px 16px;
    margin-top: 40px;
  }
}
</style>
