// client/src/components/User/Login.vue
<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import MainLayout from '@/layouts/MainLayout.vue';

const router = useRouter();
const apiPath = import.meta.env.VITE_API_PATH;


const username = ref('');
const password = ref('');
const errorMessage = ref('');

const handleLogin = async () => {
    try {
        errorMessage.value = '';

        if (!apiPath) {
            console.error("API Path is not defined! Check your .env and VITE_ prefix.");
        }

        const response = await fetch(`${apiPath}/users/login`, {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({
                username: username.value,
                password: password.value
            })
        });

        const data = await response.json();

        if (!response.ok) {
            throw new Error(data.error || `Login Failed`);
        }
        console.log("Token received:", data.token);
        localStorage.setItem('token', data.token);
        localStorage.setItem('username', data.username);

        router.push('/businesses');
    } catch (error) {
        errorMessage.value = error.message;
    }
};

</script>

<template>
    <MainLayout>
        <section class="login-container">
            <div class="login-box">
                <h2>Login</h2>
                
                <form @submit.prevent="handleLogin">
                    <div class="form-group">
                        <label>Username</label>
                        <input v-model="username" type="text" required placeholder="Enter username">
                    </div>

                    <div class="form-group">
                        <label>Password</label>
                        <input v-model="password" type="password" required placeholder="Enter password">
                    </div>

                    <p v-if="errorMessage" class="error">{{ errorMessage }}</p>

                    <button type="submit" class="login-btn">Sign In</button>
                </form>
            </div>
        </section>
    </MainLayout>
</template>

<style scoped>
.login-container {
    display: flex;
    justify-content: center;
    padding: 50px;
}
.login-box {
    width: 300px;
    padding: 20px;
    border: 1px solid #ddd;
    border-radius: 8px;
}
.form-group { margin-bottom: 15px; }
input { width: 100%; padding: 8px; margin-top: 5px; }
.error { color: red; font-size: 0.8rem; }
.login-btn { width: 100%; cursor: pointer; }
</style>

// client/src/components/Login.tsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";

const API_PATH = import.meta.env.VITE_API_PATH;

const Login = () => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const naviagate = useNavigate();
  const borderColor = error ? "border-red-500" : "border-gray-300";

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const response = await fetch(`${API_PATH}/users/login`, {
        method: "post",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, password }),
      });
      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.message || "Login failed");
      }

      const { token, username: returnedUsername, id } = await response.json();

      console.log("Username:", returnedUsername);

      localStorage.setItem("token", token);
      localStorage.setItem("username", returnedUsername);
      localStorage.setItem("id", id);

      naviagate("/businesses");
    } catch (err) {
      setError(err instanceof Error ? err.message : "An error occurred");
    } finally {
      setLoading(false);
    }
  };
  return (
    <div className="w-full max-w-xs">
      <form
        className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
        onSubmit={handleSubmit}
      >
        <div className="mb-4">
          <label
            className="block text-gray-900 text-sm font-bold mb-2"
            htmlFor="username"
          >
            Username
          </label>
          <input
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            id="username"
            type="text"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            placeholder="Username"
            required
          />
        </div>
        <div className="mb-6">
          <label
            className="block text-gray-900 text-sm font-bold mb-2"
            htmlFor="password"
          >
            Password
          </label>
          <input
            className={`shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline ${borderColor}`}
            id="password"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="Password"
            required
          />
          {error && <p className="text-red-500 text-xs italic">{error}</p>}
        </div>

        <div className="flex items-center justify-center">
          <button
            className="bg-black hover:bg-yellow-500 text-white hover:text-black font-bold py-2 px-8 rounded focus:outline-none focus:shadow-outline transition-colors delay-20 duration-300"
            type="submit"
            disabled={loading}
          >
            {loading ? "Loggin in..." : "Login"}
          </button>
        </div>
      </form>
      <div className="items-center">
        <p>
          Don't have an account?{" "}
          <Link className="font-bold text-blue-500" to="/register">
            Register
          </Link>
        </p>
      </div>
    </div>
  );
};

export default Login;
